name: bmi_calculator_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^1.0.7

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  firebase_core: ^0.4.2
  firebase_auth: ^0.14.0+9
  cloud_firestore: ^0.12.10
  flutter_spinkit: ^4.0.0
  rflutter_alert: ^1.0.3
  google_sign_in: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_text_kit: ^1.3.1

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700 # Bold
