name: bmi_calculator_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  flutter_spinkit: ^4.0.0
  rflutter_alert: ^1.0.3
  google_sign_in: ^4.5.5
  provider: ^4.3.1
  apple_sign_in: ^0.1.0
  animated_text_kit: ^2.2.0
  simple_animations: ^2.2.1
  supercharged: ^1.10.0
  delayed_display: ^1.0.3
  fancy_on_boarding: ^1.6.0
  intro_views_flutter: '^2.8.1'
  intl: ^0.16.1
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700 # Bold
